config/routes.rb
SprintStats::Application.routes.draw do

  root :to => 'static_pages#home'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  resources :sprint_results

  resources :sprints

  resources :teams

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

    @today = Date.today

    @current_sprint_results = 
      SprintResult
        .joins(:sprint)
        .where(["sprints.end >= ? AND sprints.start <= ?", @today, @today])
        .order("sprints.id ASC, sprints.start ASC")
        .includes(:sprint, :team)

    @teams = Team.includes(:team_stats)


    respond_to do |format|
      format.html 
      format.json { render json: @current_sprint_results}
    end

    
  end

  def help
  end

  def about 
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Sprint Stats</h1>
<p>This is the about page for the Sprint Stats app.</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Sprint Stats Help</h1>
<p>This is the help page for the Sprint Stats app.</p>

app/views/static_pages/home.html.erb
<h2 class='center'>Current Sprints</h2>
<p class='center'><%= @today.to_formatted_s(:long_ordinal) %></p>
<table class="table">
  <thead>
    <tr>
      <th>Sprints</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr> 
  </thead>
  <tbody>
<% 
  last_sprint_id = nil
  @current_sprint_results.each do |result| 
%>
  <% if last_sprint_id != result.sprint_id %>
    <tr class="info">
      <td>Sprint <%= result.sprint.name %> 
      <td> 
          <%= result.sprint.start.to_formatted_s(:long_ordinal) %> -
          <%= result.sprint.end.to_formatted_s(:long_ordinal) %> 
      </td> 
      <td><%= result.sprint.work_days %> work days</td>
      <td></td>
      <td class='actions'>
        <%= link_to(content_tag(:i, '', :class => 'icon-eye-open'), result.sprint) %> |
        <%= link_to(content_tag(:i, '', :class => 'icon-pencil'), edit_sprint_path(result.sprint)) %>
      </td>
    </tr>
  <% end %>
    <tr>
      <td></td>
      <td><%= result.team.name %>
      <td>Points: <%= result.points_planned %></td>
      <td>Person days: <%= result.person_days_planned %></td>
      <td class='actions'>
        <%= link_to(content_tag(:i, '', :class => 'icon-eye-open'), result) %> |
        <%= link_to(content_tag(:i, '', :class => 'icon-pencil'), edit_sprint_result_path(result)) %>
      </td>
    </tr>
  <% last_sprint_id = result.sprint_id %>
<% end %>
    <tr>
      <td></td>
      <td colspan=4><%= link_to 'Add a team to this sprint', new_sprint_result_path, :class => "btn btn-mini" %></td>
    </tr>
  </tbody>
</table>

<h2 class='center'>Teams</h2>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Product owner</th>
      <th>&oslash; pts completed</th>
      <th>% planned pts completed</th>
      <th>&oslash; pts / person day</th>
      <th>% person days</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% @teams.each do |team| %>
    <tr>
      <td><%= team.name %></td>
      <td><%= team.product_owner %></td>
      <% if (!team.team_stats.nil?) %>
        <td>
          <% if (!team.team_stats.points_actual_mean_last_5.nil?) %>
          <%= number_with_precision(team.team_stats.points_actual_mean_last_5, :precision => 2) %>
          <small class='muted'>
            &plusmn;
            <%= number_with_precision(team.team_stats.points_actual_std_dev_last_5, :precision => 2) %>
          </small>
          <% end %>
        </td>
        <td>
          <% if (!team.team_stats.percent_points_completed_mean_last_5.nil?) %>
          <%= number_with_precision(team.team_stats.percent_points_completed_mean_last_5, :precision => 0) %>
          <small class='muted'>
            &plusmn;
            <%= number_with_precision(team.team_stats.percent_points_completed_std_dev_last_5, :precision => 0) %>
          </small>
          <% end %>
        </td>
          
        <td>
          <% if (!team.team_stats.points_per_person_day_actual_mean_last_5.nil?) %>
          <%= number_with_precision(team.team_stats.points_per_person_day_actual_mean_last_5, :precision => 2)%>
          <small class='muted'>
            &plusmn;
            <%= number_with_precision(team.team_stats.points_per_person_day_actual_std_dev_last_5, :precision => 2) %>
          </small>
          <% end %>
        </td>
        <td>
          <% if (!team.team_stats.percent_person_days_achieved_mean_last_5.nil?) %>
          <%= number_with_precision(team.team_stats.percent_person_days_achieved_mean_last_5, :precision => 0) %>
          <small class='muted'>
            &plusmn;
            <%= number_with_precision(team.team_stats.percent_person_days_achieved_std_dev_last_5, :precision => 0) %>
          </small>
          <% end %>
        </td>
      <% else %>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      <% end %>
      <td class='actions'>
        <%= link_to(content_tag(:i, '', :class => 'icon-eye-open'), team) %> |
        <%= link_to(content_tag(:i, '', :class => 'icon-pencil'), edit_team_path(team)) %>
    </tr>
<% end %>
  </tbody>
</table>
<small class='muted'>* Statistics based on last 5 completed sprints.</small>
<br/>
<br/>
<br/>


<div class='alert alert-info'>
  <h3>What would you like to do?</h3>
  <div class='btn-group'>
    <%= link_to 'Add a new team', new_team_path, :class => "btn" %>
    <%= link_to 'Add a new sprint', new_sprint_path, :class => "btn" %>
    <%= link_to 'Add a team to a sprint', new_sprint_result_path, :class => "btn" %>
  </div>
</div>


<!--
# current sprints (teams registered for sprint?)
# what if no current sprints?
add my team to sprint
# add sprint

# teams with stats
# link to view team
# add team

#link to sprint results?
-->