config/routes.rb
SprintStats::Application.routes.draw do

  root :to => 'static_pages#home'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  resources :sprint_results

  resources :sprints

  resources :teams

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: "#{flash_class(key)}") %>
  <!--div class="<%= flash_class(key) %>">
    <%= value %>
  </div-->
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><a href="http://news.ycombinator.com/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <!--%= link_to "sprint stats", '#', id: "logo" %-->
      <%= link_to image_tag("logo_250.png", alt: "Searchmetrics Sprint Stats"), root_path, id:"logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Sprint Stats", root_path %></li>
          <li><%= link_to "Teams",        teams_path %></li>
          <li><%= link_to "Sprints",      sprints_path %></li>
          <li><%= link_to "Results",      sprint_results_path%></li>
          <li><%= link_to "Help",         help_path%></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
 </head>
 <body>
   <%= render 'layouts/header' %>
   <div class="container">
     <%= yield %>
   </div>
</body>
</html>